class AddCupGroupToTeams < ActiveRecord::Migration
  def change
    add_column :teams, :cup_group, :string, :limit => 1
    Team.find_by(:cup_id => 1, :name => 'France').update_attributes(cup_group: 'A') 
    Team.find_by(:cup_id => 1, :name => 'Switzerland').update_attributes(cup_group: 'A') 
    Team.find_by(:cup_id => 1, :name => 'Albania').update_attributes(cup_group: 'A') 
    Team.find_by(:cup_id => 1, :name => 'Romania').update_attributes(cup_group: 'A') 
    Team.find_by(:cup_id => 1, :name => 'Wales').update_attributes(cup_group: 'B') 
    Team.find_by(:cup_id => 1, :name => 'England').update_attributes(cup_group: 'B') 
    Team.find_by(:cup_id => 1, :name => 'Slovakia').update_attributes(cup_group: 'B') 
    Team.find_by(:cup_id => 1, :name => 'Russia').update_attributes(cup_group: 'B') 
    Team.find_by(:cup_id => 1, :name => 'Germany').update_attributes(cup_group: 'C') 
    Team.find_by(:cup_id => 1, :name => 'Poland').update_attributes(cup_group: 'C') 
    Team.find_by(:cup_id => 1, :name => 'Northern Ireland').update_attributes(cup_group: 'C') 
    Team.find_by(:cup_id => 1, :name => 'Ukraine').update_attributes(cup_group: 'C') 
    Team.find_by(:cup_id => 1, :name => 'Croatia').update_attributes(cup_group: 'D') 
    Team.find_by(:cup_id => 1, :name => 'Spain').update_attributes(cup_group: 'D') 
    Team.find_by(:cup_id => 1, :name => 'Turkey').update_attributes(cup_group: 'D') 
    Team.find_by(:cup_id => 1, :name => 'Czech Republic').update_attributes(cup_group: 'D') 
    Team.find_by(:cup_id => 1, :name => 'Italy').update_attributes(cup_group: 'E') 
    Team.find_by(:cup_id => 1, :name => 'Belgium').update_attributes(cup_group: 'E') 
    Team.find_by(:cup_id => 1, :name => 'Republic of Ireland').update_attributes(cup_group: 'E') 
    Team.find_by(:cup_id => 1, :name => 'Sweden').update_attributes(cup_group: 'E') 
    Team.find_by(:cup_id => 1, :name => 'Hungary').update_attributes(cup_group: 'F') 
    Team.find_by(:cup_id => 1, :name => 'Iceland').update_attributes(cup_group: 'F') 
    Team.find_by(:cup_id => 1, :name => 'Portugal').update_attributes(cup_group: 'F') 
    Team.find_by(:cup_id => 1, :name => 'Austria').update_attributes(cup_group: 'F') 

    Team.find_by(:cup_id => 2, :name => 'Russia').update_attributes(cup_group: 'A') 
    Team.find_by(:cup_id => 2, :name => 'Saudi Arabia').update_attributes(cup_group: 'A') 
    Team.find_by(:cup_id => 2, :name => 'Egypt').update_attributes(cup_group: 'A') 
    Team.find_by(:cup_id => 2, :name => 'Uruguay').update_attributes(cup_group: 'A') 
    Team.find_by(:cup_id => 2, :name => 'Portugal').update_attributes(cup_group: 'B') 
    Team.find_by(:cup_id => 2, :name => 'Spain').update_attributes(cup_group: 'B') 
    Team.find_by(:cup_id => 2, :name => 'Morocco').update_attributes(cup_group: 'B') 
    Team.find_by(:cup_id => 2, :name => 'Iran').update_attributes(cup_group: 'B') 
    Team.find_by(:cup_id => 2, :name => 'France').update_attributes(cup_group: 'C') 
    Team.find_by(:cup_id => 2, :name => 'Australia').update_attributes(cup_group: 'C') 
    Team.find_by(:cup_id => 2, :name => 'Peru').update_attributes(cup_group: 'C') 
    Team.find_by(:cup_id => 2, :name => 'Denmark').update_attributes(cup_group: 'C') 
    Team.find_by(:cup_id => 2, :name => 'Argentina').update_attributes(cup_group: 'D') 
    Team.find_by(:cup_id => 2, :name => 'Iceland').update_attributes(cup_group: 'D') 
    Team.find_by(:cup_id => 2, :name => 'Croatia').update_attributes(cup_group: 'D') 
    Team.find_by(:cup_id => 2, :name => 'Nigeria').update_attributes(cup_group: 'D') 
    Team.find_by(:cup_id => 2, :name => 'Brazil').update_attributes(cup_group: 'E') 
    Team.find_by(:cup_id => 2, :name => 'Switzerland').update_attributes(cup_group: 'E') 
    Team.find_by(:cup_id => 2, :name => 'Costa Rica').update_attributes(cup_group: 'E') 
    Team.find_by(:cup_id => 2, :name => 'Serbia').update_attributes(cup_group: 'E') 
    Team.find_by(:cup_id => 2, :name => 'Germany').update_attributes(cup_group: 'F') 
    Team.find_by(:cup_id => 2, :name => 'Mexico').update_attributes(cup_group: 'F') 
    Team.find_by(:cup_id => 2, :name => 'Sweden').update_attributes(cup_group: 'F') 
    Team.find_by(:cup_id => 2, :name => 'South Korea').update_attributes(cup_group: 'F') 
    Team.find_by(:cup_id => 2, :name => 'Belgium').update_attributes(cup_group: 'G') 
    Team.find_by(:cup_id => 2, :name => 'Panama').update_attributes(cup_group: 'G') 
    Team.find_by(:cup_id => 2, :name => 'Tunisia').update_attributes(cup_group: 'G') 
    Team.find_by(:cup_id => 2, :name => 'England').update_attributes(cup_group: 'G') 
    Team.find_by(:cup_id => 2, :name => 'Poland').update_attributes(cup_group: 'H') 
    Team.find_by(:cup_id => 2, :name => 'Senegal').update_attributes(cup_group: 'H') 
    Team.find_by(:cup_id => 2, :name => 'Colombia').update_attributes(cup_group: 'H') 
    Team.find_by(:cup_id => 2, :name => 'Japan').update_attributes(cup_group: 'H') 
  end
end
